# Generated by Django 5.1 on 2024-08-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savefile',
            old_name='pdf',
            new_name='file',
        ),
    ]
